name: Check Licenses

on:
    workflow_dispatch: {}

jobs:
  licensed:
    name: Check Licenses
    # .NET Framework requires Windows image
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    # - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
    # - run: npm install

    - uses: ruby/setup-ruby@13e7a03dc3ac6c3798f4570bfead2aed4d96abfb # v1.244.0
      with:
        ruby-version: ruby
        bundler-cache: true

    - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: 9.x

    # - uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

    - uses: licensee/setup-licensed@0d52e575b3258417672be0dff2f115d7db8771d8 # v1.3.2
      with:
        version: '5.x'

    - name: Build projects
      run: |
        pushd winforms-netframework/WindowsFormsApp1
        dotnet restore --use-lock-file
        dotnet build
        popd
        pushd classlibrary-net8/ClassLibrary1
        dotnet restore --use-lock-file
        dotnet build
        popd

    - name: Licensed environment
      run: licensed env

    - name: List licenses
      run: licensed list --licenses --format=json

    - name: Cache licenses
      run: |
        mkdir winforms-netframework/WindowsFormsApp1/.licenses
        mkdir classlibrary-net8/ClassLibrary1/.licenses
        licensed cache

    - name: Generate NOTICE
      run: |
        licensed notices
        cat winforms-netframework/WindowsFormsApp1/.licenses/NOTICE
        cat classlibrary-net8/ClassLibrary1/.licenses/NOTICE
