name: Check Licenses

on:
    workflow_dispatch: {}

jobs:
  licensed:
    name: Check Licenses
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    # - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
    # - run: npm install

    - uses: ruby/setup-ruby@13e7a03dc3ac6c3798f4570bfead2aed4d96abfb # v1.244.0
      with:
        ruby-version: ruby

    - uses: licensee/setup-licensed@0d52e575b3258417672be0dff2f115d7db8771d8 # v1.3.2
      with:
        version: '5.x'

    - run: licensed list
